services:
  - type: web
    name: yoel-ai-coach
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run mobile_logger.py --server.port $PORT --server.address 0.0.0.0
    plan: free 